## 张量的创建

In [1]:
import torch
import numpy as np

In [2]:
# 创建一个张量
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [5]:
# 创建一个张量，reshape为3行5列
torch.tensor(np.arange(15).reshape(3, 5))

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [7]:
# 创建3行4列的空的tensor，会用无用数据进行填充
torch.empty([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
# 创建3行4列的全为1的tensor
torch.ones([3, 4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [3]:
# 创建3行4列的全为0的tensor
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
# 创建3行4列的随机值的tensor，随机值的区间是[0, 1)
torch.rand([3, 4])

tensor([[0.1537, 0.0841, 0.3353, 0.8021],
        [0.1803, 0.8077, 0.3036, 0.8447],
        [0.4676, 0.5659, 0.9282, 0.3338]])

In [5]:
# 创建3行4列的随机整数的tensor，随机值的区间是[low, high)
torch.randint(low=0, high=10, size=[3, 4])

tensor([[9, 9, 1, 1],
        [1, 6, 3, 7],
        [7, 6, 0, 9]])

In [6]:
# 创建3行4列的随机数的tensor，随机值的分布式均值为0，方差为1
torch.randn([3, 4])

tensor([[ 0.0098,  1.0248, -0.5660,  0.2890],
        [ 0.1075,  0.4909,  0.0323, -2.3621],
        [ 0.3862, -1.4218,  0.6919,  0.9508]])

## 张量的属性和方法

In [8]:
a = torch.tensor([[[1]]])

In [9]:
# 获取tensor中的数据(当tensor中只有一个元素可用)
a.item()

1

In [10]:
# 将tensor转换为numpy
t = a.numpy()

In [11]:
# 获取tensor的类型
type(t)

numpy.ndarray

In [12]:
# 获取形状
a.shape

torch.Size([1, 1, 1])

In [13]:
# 获取形状
a.size()

torch.Size([1, 1, 1])

In [14]:
a = torch.tensor(np.arange(30).reshape(3, 2, 5))

In [15]:
a

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])

In [18]:
a.size(1)  # 即 reshape 中的 2

2

In [19]:
a.view([2, 3, 5])

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])

In [20]:
b = torch.tensor(np.arange(15).reshape(3, 5))

In [21]:
b

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [22]:
b.transpose(0, 1)  #直接交换行和列

tensor([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]])

In [23]:
# view 类似 numpy 中的 reshape，是一种浅拷贝，仅仅是形状发生改变
b.view(5, -1)  #把 b 展开之后等分为5分

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [24]:
a  # [3,2,5]

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])

In [25]:
a.transpose(0, 1)  # [2,3,5]

tensor([[[ 0,  1,  2,  3,  4],
         [10, 11, 12, 13, 14],
         [20, 21, 22, 23, 24]],

        [[ 5,  6,  7,  8,  9],
         [15, 16, 17, 18, 19],
         [25, 26, 27, 28, 29]]])

### 切片

In [26]:
b[1, :]

tensor([5, 6, 7, 8, 9])

In [27]:
b[1]

tensor([5, 6, 7, 8, 9])

In [28]:
b

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [29]:
b[:, 1]

tensor([ 1,  6, 11])

In [30]:
b[:, 1] = 100

In [31]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13,  14]])

In [32]:
b[-1, -1] = 100

In [33]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]])

In [34]:
b[-1, -1]

tensor(100)

In [35]:
c = {100: 10, 20: 10}

In [36]:
# 使用从 b 中提取的标量值作为索引，访问 c 中对应的元素。
c[b.numpy()[-1, -1]]

10

In [37]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]])

In [38]:
# 获取最大值
b.max()

tensor(100)

In [39]:
# 获取阶数
b.dim()

2

In [45]:
# 的作用是获取沿最后一个维度的最大值对应的索引张量
b.max(dim=-1)[-1]

tensor([1, 1, 1])

In [43]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]])

### 数据类型

In [46]:
# 获取tensor的数据类型
torch.FloatTensor([1, 2, 3]).dtype

torch.float32

In [47]:
a = torch.tensor([1, 2, 3])

In [48]:
# 创建数据的时候指定类型
torch.ones([2, 3], dtype=torch.float32)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [49]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]])

### 其他操作

In [50]:
b.new_ones(size=b.size())

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [58]:
b.zero_()

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [59]:
b

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [60]:
b.add(1)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [61]:
b

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [62]:
b.add_(1)  # 带下划线的方法会对x进行就地修改

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [63]:
b

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

## cuda类型的tensor

In [64]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [65]:
device

device(type='cuda')

In [66]:
a.device

device(type='cpu')

In [67]:
a = a.to(device)

In [68]:
a

tensor([1, 2, 3], device='cuda:0')

In [69]:
# 将张量 a 移动到 CPU 上（如果它不在 CPU 上）
a.cpu().device

device(type='cpu')

In [70]:
b = torch.tensor([0, 0, 0])

In [71]:
b

tensor([0, 0, 0])

In [72]:
a + b.to(device)

tensor([1, 2, 3], device='cuda:0')

In [73]:
a.cpu().numpy()

array([1, 2, 3])