In [1]:
import numpy as np

# 1 创建

In [2]:
score = np.array(
[[80, 89, 86, 67, 79],
[78, 97, 89, 67, 81],
[90, 94, 78, 67, 74],
[91, 91, 90, 67, 69],
[76, 87, 75, 67, 86],
[70, 79, 84, 67, 84],
[94, 92, 93, 67, 64],
[86, 85, 83, 67, 80]])

In [3]:
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

# 2 效率对比

In [4]:
import random
import time
import numpy as np
a = []
for i in range(100000000):
    a.append(random.random())

# 通过%time魔法方法, 查看当前行的代码运行一次所花费的时间
%time sum1=sum(a)

b=np.array(a)

%time sum2=np.sum(b)

CPU times: total: 109 ms
Wall time: 301 ms
CPU times: total: 0 ns
Wall time: 56.3 ms


# 3 ndarry的属性

In [8]:
score.shape  # 数组的维度，第一个参数是行，第二个参数是列

(8, 5)

In [9]:
score.ndim  # 数组维数

2

In [10]:
score.size  # 数组中的元素数量

40

In [11]:
score.itemsize  # 一个数组元素的长度（字节）

4

In [12]:
score.dtype  # 数组元素的类型

dtype('int32')

# 4 ndarry的形状

In [13]:
a = np.array([[1,2,3],[4,5,6]])

In [14]:
b = np.array([1,2,3,4])

In [15]:
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [16]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a.shape

(2, 3)

In [20]:
b

array([1, 2, 3, 4])

In [21]:
b.shape

(4,)

In [22]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [23]:
c.shape

(2, 2, 3)

In [24]:
a32 = np.array([[1, 2, 3],[4, 5, 6]], dtype=np.float32)

In [25]:
a32.itemsize

4

In [26]:
a.itemsize

4

In [27]:
arr = np.array(['python', 'tensorflow', 'scikit-learn', 'numpy'], dtype = np.string_)

In [28]:
arr

array([b'python', b'tensorflow', b'scikit-learn', b'numpy'], dtype='|S12')