In [1]:
import numpy as np

# 1 逻辑运算

In [2]:
stock_change = np.random.normal(0, 1, (8, 10))

In [3]:
stock_change

array([[ 0.85848086, -1.48644228,  0.64789524,  1.06635553, -0.05076336,
         0.4245672 , -1.64936182, -0.20526267,  0.37906179,  0.19465065],
       [ 1.01649917, -0.49663145, -2.0723559 ,  0.7849213 , -0.73893715,
         0.26082083,  0.50152405, -1.6935424 , -0.24491688, -1.71176536],
       [-0.26146325, -0.02172744,  1.21744779,  0.91392038, -1.66770048,
         0.24255593,  0.683626  ,  1.04720288,  0.5191152 , -0.15288127],
       [ 1.19631508, -2.08482455, -1.65046805,  0.47141738, -1.49488494,
         0.53107113, -0.31911715,  1.45692605, -0.40050991, -0.09334368],
       [ 0.23084687, -1.46092951,  0.4711128 , -0.90958163,  0.22160187,
        -0.52045093,  1.20395945, -0.21272408,  0.01742941,  1.33621493],
       [-0.66036472, -0.5730347 , -0.33323774,  0.47017441, -1.14116859,
        -1.27910262, -0.88712875,  0.33731547,  1.67852053, -0.65727285],
       [-0.10071421,  0.87619751, -0.60027529, -1.40680079,  0.58274316,
         0.52636417, -0.22734125, -0.69342089

In [4]:
stock_c = stock_change[0:5, 0:5]  # 获取前五行的前五个数

In [5]:
stock_c

array([[ 0.85848086, -1.48644228,  0.64789524,  1.06635553, -0.05076336],
       [ 1.01649917, -0.49663145, -2.0723559 ,  0.7849213 , -0.73893715],
       [-0.26146325, -0.02172744,  1.21744779,  0.91392038, -1.66770048],
       [ 1.19631508, -2.08482455, -1.65046805,  0.47141738, -1.49488494],
       [ 0.23084687, -1.46092951,  0.4711128 , -0.90958163,  0.22160187]])

In [6]:
stock_c > 1  # 判断大于 1 的值

array([[False, False, False,  True, False],
       [ True, False, False, False, False],
       [False, False,  True, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [7]:
stock_c[stock_c > 1] = 1  # 满足要求时进行赋值

In [8]:
stock_c

array([[ 0.85848086, -1.48644228,  0.64789524,  1.        , -0.05076336],
       [ 1.        , -0.49663145, -2.0723559 ,  0.7849213 , -0.73893715],
       [-0.26146325, -0.02172744,  1.        ,  0.91392038, -1.66770048],
       [ 1.        , -2.08482455, -1.65046805,  0.47141738, -1.49488494],
       [ 0.23084687, -1.46092951,  0.4711128 , -0.90958163,  0.22160187]])

In [9]:
stock_change  # 注意，会对原来的值也进行了修改

array([[ 0.85848086, -1.48644228,  0.64789524,  1.        , -0.05076336,
         0.4245672 , -1.64936182, -0.20526267,  0.37906179,  0.19465065],
       [ 1.        , -0.49663145, -2.0723559 ,  0.7849213 , -0.73893715,
         0.26082083,  0.50152405, -1.6935424 , -0.24491688, -1.71176536],
       [-0.26146325, -0.02172744,  1.        ,  0.91392038, -1.66770048,
         0.24255593,  0.683626  ,  1.04720288,  0.5191152 , -0.15288127],
       [ 1.        , -2.08482455, -1.65046805,  0.47141738, -1.49488494,
         0.53107113, -0.31911715,  1.45692605, -0.40050991, -0.09334368],
       [ 0.23084687, -1.46092951,  0.4711128 , -0.90958163,  0.22160187,
        -0.52045093,  1.20395945, -0.21272408,  0.01742941,  1.33621493],
       [-0.66036472, -0.5730347 , -0.33323774,  0.47017441, -1.14116859,
        -1.27910262, -0.88712875,  0.33731547,  1.67852053, -0.65727285],
       [-0.10071421,  0.87619751, -0.60027529, -1.40680079,  0.58274316,
         0.52636417, -0.22734125, -0.69342089

# 2 通用判断运算

In [10]:
stock_d = stock_change[6:, 0:5]

In [11]:
stock_d

array([[-0.10071421,  0.87619751, -0.60027529, -1.40680079,  0.58274316],
       [ 0.73118987, -1.34326288, -2.3661712 ,  0.78272508,  0.62740753]])

In [12]:
np.all(stock_d > 0)  # 当全部大于 0 时，返回 True

False

In [13]:
np.any(stock_d > 0)  # 当有一个或以上的值大于 0 时，返回 True

True

# 3 np.where（三元运算符）

In [14]:
np.where(stock_d > 0, 1, 0)  # 判断数组中的值。如果大于0的置为1，否则为0。三个参数分别为np.where(判断条件，为真时的值，为假时的值)

array([[0, 1, 0, 0, 1],
       [1, 0, 0, 1, 1]])

#### 复合逻辑需要结合 np.logical_and 和 np.logical_or 使用

In [15]:
# 判断数组中的值，大于0.5且小于1的换为1，否则为0
np.where(np.logical_and(stock_d > 0.5, stock_d < 1), 1, 0)

array([[0, 1, 0, 0, 1],
       [1, 0, 0, 1, 1]])

In [16]:
# 判断数组中的值，大于0.5或小于0.1的换为1，否则为0
np.where(np.logical_or(stock_d > 0.5, stock_d < 0.1), 1, 0)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 4 统计运算

In [17]:
stock_change

array([[ 0.85848086, -1.48644228,  0.64789524,  1.        , -0.05076336,
         0.4245672 , -1.64936182, -0.20526267,  0.37906179,  0.19465065],
       [ 1.        , -0.49663145, -2.0723559 ,  0.7849213 , -0.73893715,
         0.26082083,  0.50152405, -1.6935424 , -0.24491688, -1.71176536],
       [-0.26146325, -0.02172744,  1.        ,  0.91392038, -1.66770048,
         0.24255593,  0.683626  ,  1.04720288,  0.5191152 , -0.15288127],
       [ 1.        , -2.08482455, -1.65046805,  0.47141738, -1.49488494,
         0.53107113, -0.31911715,  1.45692605, -0.40050991, -0.09334368],
       [ 0.23084687, -1.46092951,  0.4711128 , -0.90958163,  0.22160187,
        -0.52045093,  1.20395945, -0.21272408,  0.01742941,  1.33621493],
       [-0.66036472, -0.5730347 , -0.33323774,  0.47017441, -1.14116859,
        -1.27910262, -0.88712875,  0.33731547,  1.67852053, -0.65727285],
       [-0.10071421,  0.87619751, -0.60027529, -1.40680079,  0.58274316,
         0.52636417, -0.22734125, -0.69342089

In [18]:
stock_change.max()  # 返回所有数组中最大的值

1.6785205288222582

In [19]:
stock_change.max(axis=1)  # 返回各行中最大的值

array([1.        , 1.        , 1.04720288, 1.45692605, 1.33621493,
       1.67852053, 0.87619751, 1.44699869])

In [20]:
stock_change.max(axis=0)  # 返回各列中最大的值

array([1.        , 0.87619751, 1.        , 1.        , 0.62740753,
       1.44699869, 1.20395945, 1.45692605, 1.67852053, 1.33621493])

In [21]:
stock_c.argmax()  # 返回最大值的下标

3

In [22]:
stock_c.argmax(axis=1)  # 返回各行最大值的下标

array([3, 0, 2, 0, 2], dtype=int64)

In [23]:
stock_c.argmax(axis=0)  # 返回各列最大值的下标

array([1, 2, 2, 0, 4], dtype=int64)

In [24]:
stock_c.argmin(axis=1)  # 返回各行最小值的下标

array([1, 2, 4, 1, 1], dtype=int64)

# 5 数组运算

In [26]:
arr = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])

In [27]:
arr + 1

array([[2, 3, 4, 3, 2, 5],
       [6, 7, 2, 3, 4, 2]])

In [28]:
arr

array([[1, 2, 3, 2, 1, 4],
       [5, 6, 1, 2, 3, 1]])

In [29]:
arr / 2

array([[0.5, 1. , 1.5, 1. , 0.5, 2. ],
       [2.5, 3. , 0.5, 1. , 1.5, 0.5]])

In [30]:
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

In [31]:
# arr1 + arr2 不可以运算

In [32]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [33]:
arr1

array([[1, 2, 3, 2, 1, 4],
       [5, 6, 1, 2, 3, 1]])

In [34]:
arr2

array([[1],
       [3]])

In [37]:
arr1 + arr2  # 利用广播机制

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])

In [38]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

In [39]:
b = np.array([[0.7], [0.3]])

In [40]:
np.dot(a, 10)

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [820, 900],
       [780, 800],
       [920, 940]])

In [41]:
np.matmul(a, b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [42]:
np.dot(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [43]:
np.matmul(a, 10)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

#### np.matmul和np.dot的区别:
* 二者都是矩阵乘法。 
* np.matmul中禁止矩阵与标量的乘法，但是 dot 允许。
* 在矢量乘矢量的內积运算中，np.matmul与np.dot没有区别。